web:
  build: ./webapp
  ports:
   - "8080:8080"
db:
  image: mongo:3.0.2
  command: mongod --dbpath /data/db --smallfiles
  volumes:
      - "db-data:/data/db"
volumes:
  db-data:

fingerprint:
  build: ./fingerprint
  ports:
   - "5000:5000"
  volumes:
       - .:/code