#specify the versuion capabilities
version: "1"

#specify the services
services:
  #teh web application
  docker_storage:
    image: "web_app"
    build: ./webapp
    expose:
      - 8080
    ports:
      - "8080:8080"  
    environment:
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
  db:
    image: mongo:3.0.2
    command: mongod --dbpath /data/db --smallfiles
    volumes:
        - "db-data:/data/db"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:


