#specify the version capabilities
# let's use version 3 (changed by Ilya)
version: "3"

#specify the services
services:
  web:
    build: ./webapp
    ports:
     - "8080:8080"
     - "80:80"
    links:
      - suggest-server
    networks:
      - front-end
    deploy:
      placement:
        constraints: [node.role == manager] 


volumes:
  db-data:
