---
swagger: "2.0"
info:
  description: "Draft of the Suggestion API"
  version: "1.0.0"
  title: "Music Suggestion API"
basePath: "/v1"
paths:
  /{artist_name}:
    get:
      tags:
      - "artist_suggestion"
      summary: "Get similar artists list"
      description: ""
      operationId: "get_suggestion"
      produces:
      - "application/json"
      parameters:
      - name: "artist_name"
        in: "path"
        description: "Artist to be searched"
        required: true
        type: "string"
      responses:
        200:
          description: "List of recommended artists"
          schema:
            $ref: "#/definitions/artistList"
        404:
          description: "Artist not found"
          schema:
            $ref: "#/definitions/artistNotFound"
        502:
          description: "Bad gateway - part of the service is down"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/defaultErrorResponse"
      x-swagger-router-controller: "swagger_server.controllers.artist_suggestion_controller"
definitions:
  artist:
    required:
    - "name"
    - "score"
    properties:
      name:
        type: "string"
      score:
        type: "number"
        format: "float"
  artistList:
    required:
    - "artists"
    properties:
      artists:
        type: "array"
        items:
          $ref: "#/definitions/artist"
  artistNotFound:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
        enum:
        - "artist_name"
      message:
        type: "string"
    description: "Error when artist not found"
  defaultErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
